services:
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: 
      grpcserver:0.1
    ports:
      - 44044:44044
    environment:
      - CONFIG_PATH=./config/local.yaml
    
  postgres:
    image: postgres:17.3
    environment:
      - POSTGRES_USER=AnikinSimon
      - POSTGRES_PASSWORD=MyPassword
      - POSTGRES_DB=sso
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d core"]
      interval: 3s
      timeout: 2s
      retries: 2

volumes:
  postgres: